import {premisesForBusiness} from './shop-premises.mjs';
import { directoryEntries, directoryClusters, directoryCopy } from './business-directory.mjs';

export const mapCopy = {
 en: { title:'Explore TPK Park', lead:'Find a showroom, plan your next stop, or discover another side of Taman Perindustrian Kinrara.', list:'List', map:'Map', open:'Explore the map', street:'Show street', reset:'Reset view', transport:'Access & Transport', food:'Food & Beverage', points:'transport point', unlocated:'Exact pins awaiting verification', status:'Street shown · exact position not yet verified', intro:'Select a business to highlight its street. Exact business pins are being verified; use the address and external directions to plan your visit.', scope:'Selected businesses and useful access points. This is an orientation map, not a survey or an ownership boundary.', unavailable:'The map could not load. Business guides and directions remain available below.', select:'Select a business from the list', close:'Close details', addressMap:'Search current address', directions:'Directions', share:'Copy link', copied:'Link copied', copyFail:'Copy the address from your browser', inFront:'In front of Jazmina Bistro, 23 Jalan TPK 2/8', drt:'DRT pickup point', drtNote:'On-call transport pickup in front of Jazmina Bistro. Check the current service before travelling; fares, booking arrangements and operating hours are not confirmed here.', pin:'View on TPK map', zoomIn:'Zoom in', zoomOut:'Zoom out', north:'North', summary:'businesses', detail:'Location details', cleared:'Selection cleared by filters', roads:'Roads and building context', data:'Map data (ODbL)' },
 ms: { title:'Terokai TPK Park', lead:'Cari bilik pameran, rancang persinggahan seterusnya atau terokai Taman Perindustrian Kinrara.', list:'Senarai', map:'Peta', open:'Terokai peta', street:'Lihat jalan', reset:'Tetapkan semula peta', transport:'Akses & Pengangkutan', food:'Makanan & Minuman', points:'titik pengangkutan', unlocated:'Pin tepat menunggu pengesahan', status:'Jalan dipaparkan · kedudukan tepat belum disahkan', intro:'Pilih perniagaan untuk melihat jalannya. Pin perniagaan sedang disahkan; gunakan alamat dan pautan arah untuk merancang lawatan.', scope:'Perniagaan terpilih dan titik akses. Peta orientasi ini bukan pelan ukur atau sempadan pemilikan.', unavailable:'Peta tidak dapat dimuatkan. Panduan perniagaan dan arah masih tersedia di bawah.', select:'Pilih perniagaan daripada senarai', close:'Tutup butiran', addressMap:'Cari alamat semasa', directions:'Arah', share:'Salin pautan', copied:'Pautan disalin', copyFail:'Salin alamat daripada pelayar anda', inFront:'Di hadapan Jazmina Bistro, 23 Jalan TPK 2/8', drt:'Titik pengambilan DRT', drtNote:'Titik pengambilan pengangkutan atas permintaan di hadapan Jazmina Bistro. Semak perkhidmatan semasa sebelum perjalanan; tambang, tempahan dan waktu operasi tidak disahkan di sini.', pin:'Lihat pada peta TPK', zoomIn:'Zum masuk', zoomOut:'Zum keluar', north:'Utara', summary:'perniagaan', detail:'Butiran lokasi', cleared:'Pilihan dikosongkan oleh penapis', roads:'Jalan dan konteks bangunan', data:'Data peta (ODbL)' },
 zh: { title:'探索TPK Park', lead:'寻找展厅、规划下一站，发现Taman Perindustrian Kinrara金銮工业园的多元商家。', list:'列表', map:'地图', open:'探索地图', street:'查看街道', reset:'重置视图', transport:'交通与接驳', food:'餐饮', points:'个交通接驳点', unlocated:'精确定位待核实', status:'显示所在街道 · 具体位置尚待核实', intro:'选择商家以突出显示所在街道。商家的精确定位正在核实中；请参考地址及外部导航安排行程。', scope:'精选商家及交通接驳点。本图仅供方位参考，并非测量图或物业权属界线。', unavailable:'地图暂时无法加载，仍可使用下方商家指南及导航链接。', select:'从列表选择商家', close:'关闭详情', addressMap:'搜索现址', directions:'导航', share:'复制链接', copied:'链接已复制', copyFail:'请从浏览器复制网址', inFront:'Jazmina Bistro门前，23 Jalan TPK 2/8', drt:'DRT接驳点', drtNote:'按需交通接驳点位于Jazmina Bistro门前。出发前请核对现行服务；本页未确认票价、预约安排或服务时间。', pin:'在TPK地图查看', zoomIn:'放大', zoomOut:'缩小', north:'北', summary:'家商家', detail:'地点详情', cleared:'筛选条件已清除所选商家', roads:'道路与建筑参考', data:'地图数据（ODbL）' }
};
export const locationOverrides = Object.freeze({}); // Add only evidenced, reusable locations. Never extract coordinates from Maps URLs.
export const foodRoutes = ['motd','jazminaBistro','nuarina','yummyNyonya'];
const aliases = {kucheBath:'KBO Kuche Bath Total Home DIY Online Stock', signature:'Signature Kinrara', forseeLens:'Eyepoint Technology Forsee', jaecooServiceCentre:'Jaecoo Puchong Kinrara Service Centre'};
const addressFallback = new Set(['chooseInterior','toyokar','fadzilEnterprise','yummyNyonya','forseeLens']);
export function mapEntries(data) {
 return directoryEntries(data).map(entry => {
  const page=data.pages[entry.route];
  const street=entry.address.match(/Jalan TPK \d\/\d+/i)?.[0] || '';
  return {...entry, premises:premisesForBusiness(entry.route), id:entry.route, kind:'business', name:entry.route==='jaecooServiceCentre'?'Jaecoo Puchong Kinrara Service Centre':entry.name, street, section:street.match(/TPK (\d)/)?.[1]||null, aliases:aliases[entry.route]||'', description:page.description, coordinates:null, status:'unlocated', precision:'street-address', pointType:null, floor:null, verifiedAt:null, source: null, licence:null, ...locationOverrides[entry.route], addressFallback:addressFallback.has(entry.route)};
 });
}
export function transportEntry(locale) {
 const c=mapCopy[locale];
 return {id:'drt-pickup',kind:'poi',cluster:'transport',name:c.drt,category:c.transport,address:c.inFront,street:'Jalan TPK 2/8',description:c.drtNote,coordinates:null,status:'unlocated',precision:'street-address',pointType:'pickup',floor:null,verifiedAt:null,source:null,licence:null,map:'https://www.google.com/maps/search/?api=1&query=DRT+Pickup+Point+Taman+Perindustrian+Kinrara&query_place_id=ChIJSzWQBQBLzDERZWKmpVgLABs'};
}
export function renderParkMap(locale,data,{escapeHtml:e,routePath,link}) {
 const c=mapCopy[locale],d=directoryCopy[locale];
 const entries=[...mapEntries(data),transportEntry(locale)];
 const cards=entries.map((x,i)=>`<article class="business-directory-card park-card" data-directory-entry data-id="${x.id}" data-kind="${x.kind}" data-cluster="${x.cluster}" data-food="${foodRoutes.includes(x.id)}" data-search="${e([x.name,x.category,x.address,x.aliases,data.nav[x.cluster]||c.transport].join(' '))}">
 <p class="business-directory-cluster"><span class="park-symbol ${x.cluster}" aria-hidden="true">${{homeLiving:'□',automotive:'◇',lifestyle:'○',transport:'↗'}[x.cluster]}</span>${e(data.nav[x.cluster]||c.transport)}</p>
 <h2>${x.route?link(locale,x.route,x.name):e(x.name)}</h2><p class="business-directory-category">${e(x.category)}</p><address>${e(x.address)}</address>
 <button class="park-select" type="button" data-select="${x.id}" aria-pressed="false" hidden>${e(c.street)} <span aria-hidden="true">↗</span><span class="visually-hidden"> · ${e(x.name)}</span></button>
 <div class="business-directory-actions">${x.route?link(locale,x.route,d.guide):''}${x.map?`<a href="${e(x.map)}" target="_blank" rel="noopener noreferrer"${x.route?` data-directory-destination="${routePath('en',x.route)}"`:''}>${e(x.addressFallback?c.addressMap:c.directions)}<span class="visually-hidden"> · ${e(x.name)} (${e(data.external)})</span></a>`:''}</div></article>`).join('');
 const publicData={locale,copy:c,entries:entries.map(x=>({id:x.id,kind:x.kind,cluster:x.cluster,name:x.name,category:x.category,address:x.address,street:x.street,premises:x.premises||[],description:x.description,coordinates:x.coordinates,status:x.status,precision:x.precision,map:x.map,addressFallback:!!x.addressFallback,guide:x.route?routePath(locale,x.route):null,destination:x.route?routePath('en',x.route):null})),guideLabel:d.guide};
 return `<section class="section business-directory-section park-directory" data-business-directory id="explore"><div class="shell">
 <link rel="stylesheet" href="/css/park-map.css">
 <div class="park-heading"><div><p class="eyebrow">TPK PARK · PUCHONG</p><h2>${e(c.title)}</h2><p>${e(c.lead)}</p></div><button class="button" data-map-open hidden>${e(c.open)} <span aria-hidden="true">↗</span></button></div>
 <div class="business-directory-controls" data-directory-controls hidden><label for="directory-search">${e(d.search)}<input id="directory-search" type="search" data-directory-search placeholder="${e(d.placeholder)}" autocomplete="off"></label><label for="directory-cluster">${e(d.cluster)}<select id="directory-cluster" data-directory-cluster><option value="">${e(d.all)}</option>${directoryClusters.map(x=>`<option value="${x}">${e(data.nav[x])}</option>`).join('')}<option value="food">${e(c.food)}</option></select></label><button type="button" data-directory-reset>${e(d.reset)}</button></div>
 <div class="park-bar" data-map-toolbar hidden><label for="park-transport"><input id="park-transport" type="checkbox" data-transport checked> ${e(c.transport)}</label><div class="park-toggle" aria-label="${e(c.map)}"><button type="button" data-view="list" aria-pressed="true">${e(c.list)}</button><button type="button" data-view="map" aria-pressed="false">${e(c.map)}</button></div></div>
 <p class="business-directory-count" role="status" aria-live="polite"><span data-directory-count>${entries.length-1}</span> ${e(d.results)} <span aria-hidden="true"> · </span><span data-poi-count>1</span> ${e(c.points)}<span class="park-coverage">${e(c.unlocated)}: ${entries.length}</span></p>
 <div class="park-workspace"><div class="park-results"><p data-directory-empty hidden>${e(d.empty)}</p><div class="business-directory-grid">${cards}</div></div>
 <div class="park-map-panel" data-map-panel hidden><div class="park-map-top"><span>TPK PARK</span><button type="button" data-map-reset>${e(c.reset)} ↺</button></div><p class="park-map-intro">${e(c.intro)}</p><div class="park-canvas" data-map-canvas role="region" aria-label="${e(c.title)}"></div><p class="park-map-error" data-map-error hidden role="status">${e(c.unavailable)}</p><div class="park-map-footer"><span>↑ ${e(c.north)} · ${e(c.roads)}</span><a href="/assets/map/context.geojson">${e(c.data)}</a></div><section class="park-detail" data-map-detail aria-label="${e(c.detail)}" tabindex="-1"><p>${e(c.select)}</p></section></div></div>
 <p class="park-scope">${e(c.scope)}</p><p class="business-directory-note">${e(d.note)}</p>
 <script type="application/json" id="park-map-data">${JSON.stringify(publicData).replace(/</g,'\\u003c')}</script></div></section><script type="module" src="/js/park-directory.js"></script>`;
}
