import {managementOfficeEntry,officeCopy,officeIcon} from './management-office.mjs';
import {businessBuildings} from './building-premises.mjs';
import {premisesForBusiness} from './shop-premises.mjs';
import { directoryEntries, directoryClusters, directoryCopy } from './business-directory.mjs';

export const mapCopy = {
 en: { title:'Explore TPK Park', lead:'Find a showroom, plan your next stop, or discover another side of Taman Perindustrian Kinrara.', list:'List', map:'Map', open:'Explore the map', street:'Show location', reset:'Reset view', transport:'Access & Transport', lifestyle:'Lifestyle & Dining', points:'transport point', unlocated:'Exact pins awaiting verification', status:'Street shown · exact position not yet verified', block:'Block', occupants:'Businesses at this unit', noOccupants:'No featured business at this unit', ground:'Ground floor', first:'First floor', intro:'Shaded premises show approximate plan-based positions. Select a building or shoplot to see its businesses. Other businesses highlight their street; use the address and directions for your visit.', scope:'Selected businesses and useful access points. This is an orientation map, not a survey or an ownership boundary.', unavailable:'The map could not load. Business guides and directions remain available below.', select:'Select a business from the list', close:'Close details', addressMap:'Search current address', directions:'Directions', share:'Copy link', copied:'Link copied', copyFail:'Copy the address from your browser', inFront:'In front of Jazmina Bistro, 23 Jalan TPK 2/8', drt:'DRT pickup point', drtNote:'Trek Rides publishes a Puchong-zone fare of RM2 per ride and daily hours of 6am–10pm. Its coverage includes LRT Kinrara BK5. Book in the Trek Rides app: select the station and your TPK destination, then confirm the available trip, fare, pickup/drop-off points and ETA. The TPK pickup point is in front of Jazmina Bistro, 23 Jalan TPK 2/8.', pin:'View on TPK map', zoomIn:'Zoom in', zoomOut:'Zoom out', north:'North', summary:'businesses', detail:'Location details', cleared:'Selection cleared by filters', roads:'Roads and building context', data:'Map data (ODbL)' },
 ms: { title:'Terokai TPK Park', lead:'Cari bilik pameran, rancang persinggahan seterusnya atau terokai Taman Perindustrian Kinrara.', list:'Senarai', map:'Peta', open:'Terokai peta', street:'Lihat lokasi', reset:'Tetapkan semula peta', transport:'Akses & Pengangkutan', lifestyle:'Gaya Hidup & Tempat Makan', points:'titik pengangkutan', unlocated:'Pin tepat menunggu pengesahan', status:'Jalan dipaparkan · kedudukan tepat belum disahkan', block:'Blok', occupants:'Perniagaan di unit ini', noOccupants:'Tiada perniagaan pilihan di unit ini', ground:'Tingkat bawah', first:'Tingkat satu', intro:'Premis berlorek menunjukkan kedudukan anggaran berdasarkan pelan. Pilih bangunan atau lot kedai untuk melihat perniagaannya. Perniagaan lain menunjukkan jalan; gunakan alamat dan arah untuk kunjungan.', scope:'Perniagaan terpilih dan titik akses. Peta orientasi ini bukan pelan ukur atau sempadan pemilikan.', unavailable:'Peta tidak dapat dimuatkan. Panduan perniagaan dan arah masih tersedia di bawah.', select:'Pilih perniagaan daripada senarai', close:'Tutup butiran', addressMap:'Cari alamat semasa', directions:'Arah', share:'Salin pautan', copied:'Pautan disalin', copyFail:'Salin alamat daripada pelayar anda', inFront:'Di hadapan Jazmina Bistro, 23 Jalan TPK 2/8', drt:'Titik pengambilan DRT', drtNote:'Trek Rides menyenaraikan tambang zon Puchong sebanyak RM2 setiap perjalanan dan waktu operasi harian 6 pagi–10 malam. Liputannya termasuk LRT Kinrara BK5. Tempah melalui aplikasi Trek Rides: pilih stesen dan destinasi anda di TPK, kemudian sahkan perjalanan yang tersedia, tambang, lokasi pengambilan/penurunan dan anggaran masa ketibaan. Titik pengambilan TPK terletak di hadapan Jazmina Bistro, 23 Jalan TPK 2/8.', pin:'Lihat pada peta TPK', zoomIn:'Zum masuk', zoomOut:'Zum keluar', north:'Utara', summary:'perniagaan', detail:'Butiran lokasi', cleared:'Pilihan dikosongkan oleh penapis', roads:'Jalan dan konteks bangunan', data:'Data peta (ODbL)' },
 zh: { title:'探索TPK Park', lead:'寻找展厅、规划下一站，发现Taman Perindustrian Kinrara金銮工业园的多元商家。', list:'列表', map:'地图', open:'探索地图', street:'查看位置', reset:'重置视图', transport:'交通与接驳', lifestyle:'生活品味与餐饮', points:'个交通接驳点', unlocated:'精确定位待核实', status:'显示所在街道 · 具体位置尚待核实', block:'座', occupants:'本单位商家', noOccupants:'本单位暂无精选商家', ground:'底层', first:'一楼', intro:'阴影物业显示按图估算的位置。选择建筑或店铺可查看商家。其他商家显示所在街道；请参考地址和导航安排行程。', scope:'精选商家及交通接驳点。本图仅供方位参考，并非测量图或物业权属界线。', unavailable:'地图暂时无法加载，仍可使用下方商家指南及导航链接。', select:'从列表选择商家', close:'关闭详情', addressMap:'搜索现址', directions:'导航', share:'复制链接', copied:'链接已复制', copyFail:'请从浏览器复制网址', inFront:'Jazmina Bistro门前，23 Jalan TPK 2/8', drt:'DRT接驳点', drtNote:'Trek Rides官网公布的蒲种区票价为每程RM2，每日服务时间为早上6时至晚上10时，覆盖范围包括LRT Kinrara BK5站。请通过Trek Rides应用选择车站与TPK目的地，并确认可预约行程、票价、上下车点及预计抵达时间。TPK接驳点位于23 Jalan TPK 2/8的Jazmina Bistro门前。', pin:'在TPK地图查看', zoomIn:'放大', zoomOut:'缩小', north:'北', summary:'家商家', detail:'地点详情', cleared:'筛选条件已清除所选商家', roads:'道路与建筑参考', data:'地图数据（ODbL）' }
};
export const locationOverrides = Object.freeze({}); // Add only evidenced, reusable locations. Never extract coordinates from Maps URLs.
const aliases = {kucheBath:'KBO Kuche Bath Total Home DIY Online Stock', signature:'Signature Kinrara', forseeLens:'Eyepoint Technology Forsee', jaecooServiceCentre:'Jaecoo Puchong Kinrara Service Centre'};
const addressFallback = new Set(['chooseInterior','toyokar','fadzilEnterprise','yummyNyonya','forseeLens']);
export function mapEntries(data) {
 return directoryEntries(data).map(entry => {
  const page=data.pages[entry.route];
  const street=entry.address.match(/Jalan TPK \d\/\d+/i)?.[0] || '';
  return {...entry, premises:premisesForBusiness(entry.route), buildingIds:businessBuildings[entry.route]||[], id:entry.route, kind:'business', name:entry.route==='jaecooServiceCentre'?'Jaecoo Puchong Kinrara Service Centre':entry.name, street, section:street.match(/TPK (\d)/)?.[1]||null, aliases:aliases[entry.route]||'', description:page.description, coordinates:null, status:'unlocated', precision:'street-address', pointType:null, floor:null, verifiedAt:null, source: null, licence:null, ...locationOverrides[entry.route], addressFallback:addressFallback.has(entry.route)};
 });
}
export function transportEntry(locale) {
 const c=mapCopy[locale];
 return {id:'drt-pickup',kind:'poi',cluster:'transport',name:c.drt,category:c.transport,address:c.inFront,street:'Jalan TPK 2/8',description:c.drtNote,aliases:'Trek Rides RM2 LRT Kinrara BK5 Bandar Kinrara 5',website:'https://trekrides.com/trek-rides/',websiteLabel:{en:'Trek Rides · official service information',ms:'Trek Rides · maklumat rasmi perkhidmatan',zh:'Trek Rides官方服务资料'}[locale],coordinates:null,status:'unlocated',precision:'street-address',pointType:'pickup',floor:null,verifiedAt:null,source:null,licence:null,map:'https://www.google.com/maps/search/?api=1&query=DRT+Pickup+Point+Taman+Perindustrian+Kinrara&query_place_id=ChIJSzWQBQBLzDERZWKmpVgLABs'};
}
export function renderParkMap(locale,data,{escapeHtml:e,routePath,link}) {
 const c=mapCopy[locale],d=directoryCopy[locale];
 const entries=[...mapEntries(data),transportEntry(locale),managementOfficeEntry(locale)];
 const clusterLabel=x=>x.cluster==='management'?officeCopy[locale].category:(x.cluster==='lifestyle'?c.lifestyle:data.nav[x.cluster])||c.transport;
 const cards=entries.map((x,i)=>`<article class="business-directory-card park-card" data-directory-entry data-id="${x.id}" data-kind="${x.kind}" data-cluster="${x.cluster}" data-search="${e([x.name,x.category,x.address,x.aliases,clusterLabel(x)].join(' '))}">
 <p class="business-directory-cluster"><span class="park-symbol ${x.cluster}" aria-hidden="true">${{homeLiving:'□',automotive:'◇',lifestyle:'○',transport:'↗',management:officeIcon}[x.cluster]}</span>${e(clusterLabel(x))}</p>
 <h2>${x.route?link(locale,x.route,x.name):e(x.name)}</h2><p class="business-directory-category">${e(x.category)}</p><address>${e(x.address)}</address>${x.kind==='poi'?`<p class="${x.cluster==='management'?'park-office-description':'park-transport-description'}">${e(x.description)}</p>`:''}
 <button class="park-select" type="button" data-select="${x.id}" aria-pressed="false" hidden>${e(c.street)} <span aria-hidden="true">↗</span><span class="visually-hidden"> · ${e(x.name)}</span></button>
 <div class="business-directory-actions">${x.website?`<a href="${e(x.website)}" target="_blank" rel="noopener noreferrer">${e(x.websiteLabel)}</a>`:''}${x.route?link(locale,x.route,d.guide):x.contactRoute?link(locale,x.contactRoute,x.guideLabel):''}${x.map?`<a href="${e(x.map)}" target="_blank" rel="noopener noreferrer"${x.route?` data-directory-destination="${routePath('en',x.route)}"`:''}>${e(x.addressFallback?c.addressMap:c.directions)}<span class="visually-hidden"> · ${e(x.name)} (${e(data.external)})</span></a>`:''}</div></article>`).join('');
 const publicData={locale,copy:c,officeIcon,entries:entries.map(x=>({id:x.id,kind:x.kind,cluster:x.cluster,name:x.name,category:x.category,address:x.address,street:x.street,premises:x.premises||[],buildingIds:x.buildingIds||[],description:x.description,website:x.website,websiteLabel:x.websiteLabel,coordinates:x.coordinates,status:x.status,precision:x.precision,map:x.map,addressFallback:!!x.addressFallback,guideLabel:x.guideLabel,guide:x.route?routePath(locale,x.route):x.contactRoute?routePath(locale,x.contactRoute):null,destination:x.route?routePath('en',x.route):null})),guideLabel:d.guide};
 return `<section class="section business-directory-section park-directory" data-business-directory id="explore"><div class="shell">
 <link rel="stylesheet" href="/css/park-map.css">
 <div class="park-heading"><div><p class="eyebrow">TPK PARK · PUCHONG</p><h2>${e(c.title)}</h2><p>${e(c.lead)}</p></div><button class="button" data-map-open hidden>${e(c.open)} <span aria-hidden="true">↗</span></button></div>
 <div class="business-directory-controls" data-directory-controls hidden><label for="directory-search">${e(d.search)}<input id="directory-search" type="search" data-directory-search placeholder="${e(d.placeholder)}" autocomplete="off"></label><label for="directory-cluster">${e(d.cluster)}<select id="directory-cluster" data-directory-cluster><option value="">${e(d.all)}</option>${directoryClusters.map(x=>`<option value="${x}">${e(x==='lifestyle'?c.lifestyle:data.nav[x])}</option>`).join('')}</select></label><button type="button" data-directory-reset>${e(d.reset)}</button></div>
 <div class="park-bar" data-map-toolbar hidden><div class="park-poi-filters"><label for="park-office"><input id="park-office" type="checkbox" data-office checked> <span class="park-symbol management" aria-hidden="true">${officeIcon}</span>${e(officeCopy[locale].category)}</label><label for="park-transport"><input id="park-transport" type="checkbox" data-transport checked> ${e(c.transport)}</label></div><div class="park-toggle" aria-label="${e(c.map)}"><button type="button" data-view="list" aria-pressed="true">${e(c.list)}</button><button type="button" data-view="map" aria-pressed="false">${e(c.map)}</button></div></div>
 <p class="business-directory-count" role="status" aria-live="polite"><span data-directory-count>${entries.filter(x=>x.kind==='business').length}</span> ${e(d.results)} <span aria-hidden="true"> · </span><span data-poi-count>1</span> ${e(c.points)} <span aria-hidden="true"> · </span><span data-office-count>1</span> ${e(officeCopy[locale].count)}<span class="park-coverage">${e(c.unlocated)}: ${entries.filter(x=>x.status==='unlocated').length}</span></p>
 <div class="park-workspace"><div class="park-results"><p data-directory-empty hidden>${e(d.empty)}</p><div class="business-directory-grid">${cards}</div></div>
 <div class="park-map-panel" data-map-panel hidden><div class="park-map-top"><span>TPK PARK</span><button type="button" data-map-reset>${e(c.reset)} ↺</button></div><p class="park-map-intro">${e(c.intro)}</p><div class="park-canvas" data-map-canvas role="region" aria-label="${e(c.title)}"></div><p class="park-map-error" data-map-error hidden role="status">${e(c.unavailable)}</p><div class="park-map-footer"><span>↑ ${e(c.north)} · ${e(c.roads)}</span><a href="/assets/map/context.geojson">${e(c.data)}</a></div><section class="park-detail" data-map-detail aria-label="${e(c.detail)}" tabindex="-1"><p>${e(c.select)}</p></section></div></div>
 <p class="park-scope">${e(c.scope)}</p><p class="business-directory-note">${e(d.note)}</p>
 <script type="application/json" id="park-map-data">${JSON.stringify(publicData).replace(/</g,'\\u003c')}</script></div></section><script type="module" src="/js/park-directory.js"></script>`;
}
